In [1]:
import numpy as np
import pandas as pd

In [6]:
athletes = pd.read_csv("./data/athlete_events.csv")
athletes.head(5)

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [7]:
athletes.shape

(271116, 15)

In [10]:
athletes[athletes["Sex"] == "M"].shape

(196594, 15)

In [11]:
athletes[athletes["Sex"] == "F"].shape

(74522, 15)

In [16]:
athletes.columns

# 66 different sports
len(athletes["Sport"].unique())

66

In [22]:
print(sum(athletes["Height"].isna()))
print(sum(athletes["Weight"].isna()))

60171
62875


In [23]:
athletes_clean = athletes.dropna(subset = ["Height", "Weight"])
athletes_clean.shape

(206853, 15)

In [24]:
athletes_clean.head()

ID                      Name Sex   Age  Height  Weight         Team  NOC  \
0   1                 A Dijiang   M  24.0   180.0    80.0        China  CHN   
1   2                  A Lamusi   M  23.0   170.0    60.0        China  CHN   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0  Netherlands  NED   
5   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0  Netherlands  NED   
6   5  Christine Jacoba Aaftink   F  25.0   185.0    82.0  Netherlands  NED   

         Games  Year  Season         City          Sport  \
0  1992 Summer  1992  Summer    Barcelona     Basketball   
1  2012 Summer  2012  Summer       London           Judo   
4  1988 Winter  1988  Winter      Calgary  Speed Skating   
5  1988 Winter  1988  Winter      Calgary  Speed Skating   
6  1992 Winter  1992  Winter  Albertville  Speed Skating   

                                Event Medal  
0         Basketball Men's Basketball   NaN  
1        Judo Men's Extra-Lightweight   NaN  
4    Speed Skating Women's 500 metres   NaN  
5  Speed Skating Women's 1,000 metres   NaN  
6    Speed Skating Women's 500 metres   NaN

In [ ]:
X = athletes_clean[["Sex", "Age", "Height", "Weight"]]
y = athletes_clean["Sport"]

X.head()

Sex   Age  Height  Weight
0   M  24.0   180.0    80.0
1   M  23.0   170.0    60.0
4   F  21.0   185.0    82.0
5   F  21.0   185.0    82.0
6   F  25.0   185.0    82.0

In [47]:
sex_map = {}
sex_map['M'] = 0
sex_map['F'] = 1

sex_mapped = np.empty(X["Sex"].shape)

for i, sex in enumerate(X["Sex"]):
    sex_mapped[i] = sex_map[sex]

X["Sex_mapped"] = sex_mapped
X = X.drop("Sex", axis = 1)

X.head()



C:\Users\mtkub\AppData\Local\Temp\ipykernel_47108\975297334.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex_mapped"] = sex_mapped


Age  Height  Weight  Sex_mapped
0  24.0   180.0    80.0         0.0
1  23.0   170.0    60.0         0.0
4  21.0   185.0    82.0         1.0
5  21.0   185.0    82.0         1.0
6  25.0   185.0    82.0         1.0

In [48]:
y.head()

#Need to map Sport to an integer value

sports_map = {}
count = 0
for sport in athletes_clean["Sport"].unique():
    sports_map[sport] = count
    count += 1

sports_map

{'Basketball': 0,
 'Judo': 1,
 'Speed Skating': 2,
 'Cross Country Skiing': 3,
 'Ice Hockey': 4,
 'Badminton': 5,
 'Sailing': 6,
 'Biathlon': 7,
 'Gymnastics': 8,
 'Athletics': 9,
 'Alpine Skiing': 10,
 'Weightlifting': 11,
 'Wrestling': 12,
 'Luge': 13,
 'Rowing': 14,
 'Bobsleigh': 15,
 'Swimming': 16,
 'Football': 17,
 'Equestrianism': 18,
 'Shooting': 19,
 'Taekwondo': 20,
 'Boxing': 21,
 'Fencing': 22,
 'Diving': 23,
 'Canoeing': 24,
 'Handball': 25,
 'Water Polo': 26,
 'Tennis': 27,
 'Cycling': 28,
 'Hockey': 29,
 'Figure Skating': 30,
 'Softball': 31,
 'Archery': 32,
 'Volleyball': 33,
 'Synchronized Swimming': 34,
 'Modern Pentathlon': 35,
 'Table Tennis': 36,
 'Nordic Combined': 37,
 'Baseball': 38,
 'Rhythmic Gymnastics': 39,
 'Freestyle Skiing': 40,
 'Rugby Sevens': 41,
 'Trampolining': 42,
 'Beach Volleyball': 43,
 'Triathlon': 44,
 'Ski Jumping': 45,
 'Curling': 46,
 'Golf': 47,
 'Snowboarding': 48,
 'Short Track Speed Skating': 49,
 'Skeleton': 50,
 'Rugby': 51,
 'Tug-Of-W

In [49]:
y_new = np.empty(shape = y.shape)

for i, sport in enumerate(y):
    y_new[i] = sports_map[sport]

y_new.shape

(206853,)

In [52]:
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [53]:
random_forest = RandomForestClassifier()
XGBC = XGBClassifier(n_estimators = 10)

rf_scores = cross_val_score(random_forest, X, y_new, cv=5, scoring = 'accuracy')
xgb_scores = cross_val_score(XGBC, X, y_new, scoring = 'accuracy')
print(rf_scores)

C:\Users\mtkub\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
C:\Users\mtkub\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


[0.19329965 0.19291291 0.19707041 0.1979212  0.19598743]


In [54]:
print(xgb_scores)

[0.2766914  0.28266177 0.28150153 0.2816292  0.28774474]


In [55]:
XGBC.fit(X, y_new)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=10,
              n_jobs=None, num_parallel_tree=None, ...)

In [57]:
XGBC.predict(np.array([[21, 182, 80, 0.0]]))

array([16])

In [58]:
inv_map = {v: k for k, v in sports_map.items()}

print(inv_map[16])

Swimming


0            Basketball
1                  Judo
4         Speed Skating
5         Speed Skating
6         Speed Skating
              ...      
271111             Luge
271112      Ski Jumping
271113      Ski Jumping
271114        Bobsleigh
271115        Bobsleigh
Name: Sport, Length: 206853, dtype: object


In [ ]:

sport_counts = athletes.groupby("Sport", as_index=False).count()
print(sport_counts)
print(sport_counts.shape)

                    ID  Name   Sex   Age  Height  Weight  Team   NOC  Games  \
Sport                                                                         
Aeronautics          1     1     1     1       0       0     1     1      1   
Alpine Skiing     8829  8829  8829  8751    6394    6350  8829  8829   8829   
Alpinism            25    25    25    16       0       0    25    25     25   
Archery           2334  2334  2334  2254    1945    1886  2334  2334   2334   
Art Competitions  3578  3578  3578  3071      59      55  3578  3578   3578   
...                ...   ...   ...   ...     ...     ...   ...   ...    ...   
Tug-Of-War         170   170   170   126      25      52   170   170    170   
Volleyball        3404  3404  3404  3395    3283    3277  3404  3404   3404   
Water Polo        3846  3846  3846  3646    2788    2724  3846  3846   3846   
Weightlifting     3937  3937  3937  3731    3008    3803  3937  3937   3937   
Wrestling         7154  7154  7154  6663    5346    

In [71]:
import matplotlib.pyplot as plt
# Need another dictionary or list?????

plt.bar(sport_counts["Sport"], sport_counts["ID"])

KeyError: 'Sport'